# Generated by Django 4.2 on 2023-04-08 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cross', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(blank=True, max_length=100, null=True, verbose_name='Модель оборудования')),
                ('slag', models.SlugField(blank=True, max_length=120, null=True)),
            ],
            options={
                'verbose_name': 'Модель оборудования',
                'verbose_name_plural': 'Модели оборудования',
            },
        ),
        migrations.CreateModel(
            name='DeviceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Тип устройства')),
                ('slug', models.SlugField(blank=True, max_length=60, null=True)),
            ],
            options={
                'verbose_name': 'Тип устройства',
                'verbose_name_plural': 'Типы устройств',
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.IntegerField(verbose_name='Серийный номер')),
                ('inventary_number', models.IntegerField(verbose_name='Инвентарный номер')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP Адрес')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cross.crossroad')),
                ('device_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.devicetype')),
                ('mod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.devicemodel')),
            ],
        ),
    ]
