# Generated by Django 4.2 on 2023-04-09 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_rename_mod_device_model'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device',
            options={'verbose_name': 'Устройство', 'verbose_name_plural': 'Устройства'},
        ),
        migrations.AlterField(
            model_name='devicemodel',
            name='slag',
            field=models.SlugField(max_length=120),
        ),
    ]
