# Generated by Django 4.2 on 2023-04-09 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_alter_device_options_alter_devicemodel_slag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicemodel',
            name='slag',
            field=models.SlugField(blank=True, max_length=120, null=True),
        ),
    ]
