# Generated by Django 4.2 on 2023-04-09 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0005_remove_devicemodel_slag_devicemodel_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicemodel',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='devices.devicetype', verbose_name='Тип устройства'),
        ),
    ]
