# Generated by Django 4.2 on 2023-04-09 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0006_devicemodel_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicemodel',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Проиводитель'),
        ),
    ]
