# Generated by Django 4.2 on 2023-04-11 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0007_devicemodel_manufacturer'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='gateway',
            field=models.GenericIPAddressField(blank=True, default='192.168.70.1', null=True, verbose_name='Шлюз'),
        ),
        migrations.AddField(
            model_name='device',
            name='mask',
            field=models.GenericIPAddressField(blank=True, default='255.255.255.0', null=True, verbose_name='Маска подсети'),
        ),
        migrations.AlterField(
            model_name='device',
            name='serial_number',
            field=models.CharField(max_length=15, verbose_name='Серийный номер'),
        ),
    ]
