# Generated by Django 4.2 on 2023-04-11 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cross', '0002_alter_crossroad_address_alter_crossroad_latitude_and_more'),
        ('devices', '0008_device_gateway_device_mask_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cross.crossroad', verbose_name='Адрес установки'),
        ),
        migrations.AlterField(
            model_name='device',
            name='device_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.devicetype', verbose_name='Тип устройства'),
        ),
        migrations.AlterField(
            model_name='device',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.devicemodel', verbose_name='Модель устройства'),
        ),
    ]
