# Generated by Django 4.2 on 2023-04-11 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0010_alter_device_ip_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='inventary_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Инвентарный номер'),
        ),
    ]
