# Generated by Django 4.0.4 on 2023-04-19 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0011_alter_device_inventary_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='serial_number',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Серийный номер'),
        ),
    ]
