# Generated by Django 4.2 on 2023-04-27 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0012_alter_device_serial_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileProfile',
            fields=[
                ('device', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='mobile_profile', serialize=False, to='devices.device', verbose_name='Мобильный профиль')),
                ('phone_number', models.CharField(max_length=12, verbose_name='Номер телефона')),
                ('sim_number', models.CharField(max_length=25, verbose_name='Номер SIM карты')),
                ('pin1', models.CharField(blank=True, max_length=6, verbose_name='PIN код 1')),
                ('pin2', models.CharField(blank=True, max_length=6, verbose_name='PIN код 2')),
                ('puk1', models.CharField(blank=True, max_length=12, verbose_name='PUK код 1')),
                ('puk2', models.CharField(blank=True, max_length=12, verbose_name='PUK код 2')),
                ('serial_number', models.CharField(blank=True, max_length=20, verbose_name='Серийный номер')),
                ('dedicated_IP', models.GenericIPAddressField(blank=True, null=True, verbose_name='Выделенный IP адрес')),
                ('open_vpn_IP', models.GenericIPAddressField(blank=True, null=True, verbose_name='Open VPN IP адрес')),
            ],
            options={
                'verbose_name': 'SIM карта',
                'verbose_name_plural': 'SIM карты',
            },
        ),
        migrations.AlterField(
            model_name='devicemodel',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='devices.devicetype', verbose_name='Тип устройства'),
        ),
    ]
