# Generated by Django 4.2 on 2023-04-27 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0013_mobileprofile_alter_devicemodel_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MobileProfile',
        ),
    ]
