# Generated by Django 4.2 on 2023-04-27 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0015_mobileprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mobileprofile',
            name='device',
        ),
        migrations.AddField(
            model_name='device',
            name='mobile_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='devices.mobileprofile', verbose_name='SIM Карта'),
        ),
    ]
