# Generated by Django 4.0.4 on 2023-04-13 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_position_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='date_of_imployment',
            new_name='date_of_employment',
        ),
    ]
