# Generated by Django 4.0.4 on 2023-04-14 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_customuser_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_of_employment',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата трудоустройства'),
        ),
    ]
