# Generated by Django 4.0.4 on 2023-04-18 12:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cross', '0002_alter_crossroad_address_alter_crossroad_latitude_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_start_date', models.DateTimeField(auto_now_add=True, verbose_name='Время поступления')),
                ('task_bug_description', models.TextField(blank=True, null=True, verbose_name='Описание ошибки')),
                ('task_sender', models.CharField(blank=True, max_length=50, null=True, verbose_name='Передал заявку')),
                ('task_act_number', models.IntegerField(blank=True, null=True, verbose_name='Номер акта наряда')),
                ('task_work_description', models.TextField(blank=True, null=True, verbose_name='Выполненные работы')),
                ('task_end_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Время завершения')),
                ('task_closed', models.BooleanField(default=False, verbose_name='Закрыта')),
                ('task_crossroad_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cross.crossroad', verbose_name='Перекрёсток')),
                ('task_receiver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Принял заявку')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
            },
        ),
    ]
