# Generated by Django 4.2 on 2023-04-18 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_act_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Номер акта'),
        ),
    ]
