# Generated by Django 4.0.4 on 2023-04-19 11:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0002_alter_task_task_act_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='task_worker', to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель работ'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='task_receiver', to=settings.AUTH_USER_MODEL, verbose_name='Принял заявку'),
        ),
    ]
